import { NextResponse } from 'next/server';
import { google } from 'googleapis';
import { getServerSession } from "next-auth/next";
import { GET as authOptions } from "../../auth/[...nextauth]/route"; // Import authOptions logic if exported, or just use handler

export async function POST(req) {
    try {
        // 1. Get User Session
        // Note: getServerSession requires the auth options object. 
        // Since we exported handler as GET/POST, we might need to extract options or import them.
        // For simplicity in this structure, I'll rely on the token passed in header or session check locally if possible,
        // but typically we import authOptions. Let's assume standard behavior or client passing token if server-session fails context.

        // Better approach: Pass access token from client for this specific action if server session is complex to wire up here without authOptions export.
        // BUT, securely we should use server session.

        const body = await req.json();
        const { accessToken, name, videoIds } = body;

        if (!accessToken) {
            return NextResponse.json({ error: 'Unauthorized: No access token' }, { status: 401 });
        }

        const auth = new google.auth.OAuth2();
        auth.setCredentials({ access_token: accessToken });

        const youtube = google.youtube({ version: 'v3', auth });

        // 2. Create Playlist
        const playlistRes = await youtube.playlists.insert({
            part: 'snippet,status',
            requestBody: {
                snippet: {
                    title: name,
                    description: 'Generated by AutoYT Playlist',
                },
                status: {
                    privacyStatus: 'private', // Default to private for safety
                },
            },
        });

        const playlistId = playlistRes.data.id;

        // 3. Add Videos (Sequentially to avoid rate limits)
        let addedCount = 0;
        for (const videoId of videoIds) {
            try {
                await youtube.playlistItems.insert({
                    part: 'snippet',
                    requestBody: {
                        snippet: {
                            playlistId: playlistId,
                            resourceId: {
                                kind: 'youtube#video',
                                videoId: videoId,
                            },
                        },
                    },
                });
                addedCount++;
            } catch (e) {
                console.error(`Failed to add video ${videoId}`, e);
            }
        }

        return NextResponse.json({ success: true, playlistId, addedCount });

    } catch (error) {
        console.error('YouTube Create Error:', error);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}
